services:
  postgres:
    image: postgres:18
    container_name: store-gas-db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql
      - ../backend/db/init:/docker-entrypoint-initdb.d

  backend:
    build: ../backend
    container_name: store-gas-api
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build: ../frontend
    container_name: store-gas-client
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  pg-data: