const LogAction = Object.freeze({
    CREDIT_INCURRED: 'CREDIT_INCURRED',
    CREDIT_PARTIAL_PAYMENT: 'CREDIT_PARTIAL_PAYMENT',
    CREDIT_CLEARED: 'CREDIT_CLEARED',
    INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
    OTHER: 'OTHER'
});

module.exports = LogAction;