name: Deploy Store Gas App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync repo to app folder
        run: rsync -av --delete ./ /home/safal/store-gas/
      
      - name: Build and run containers
        run: |
          docker compose \
            --env-file /home/safal/store-gas/.env \
            -f /home/safal/store-gas/docker/docker-compose.prod.yml \
            up -d --build --remove-orphans

